- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start Nginx Service
  systemd:
    name: nginx
    state: started
    enabled: yes

- na,e: Copy Azure DevOps Repo File
  copy:
    src: azurecli.repo
    dest: /etc

- name: Install Azure CLI
  yum:
    name: [ "azure-cli", "libicu" ]
    state: latest



