- name: Install Nginx
  yum:
   name: nginx
   state: latest

- name: Start Nginx Service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy AzureDevops Reop File
  copy:
    src: azurecli.repo
    dest: /etc/yum.repos.d

- name: Install Azure CLI
  yum:
    name: [ "azure-cli", "libicu" ]
    state: latest

- name: Download Azure Artifacts
  shell: az artifacts universal download \ --organization "https://dev.azure.com/shehan567/" \ --project "8a354593-ad32-4f68-8a1d-0az artifacts universal download \ --organization "https://dev.azure.com/shehan567/" \ --project "8a354593-ad32-4f68-8a1d-0840e9706d7a" \ --scope project \ --feed "Roboshop" \ --name "frontend" \ --version "0.0.3" \ --path .840e9706d7a" \ --scope project \ --feed "Roboshop" \ --name "frontend" \ --version "0.0.3" \ --path .