- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start Nginx Service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Remove old HTDocs
  file:
    path: /usr/share/nginx/html
    state: absent

- name: Creat HtDocs Directory
  file:
    path: /usr/share/nginx/html
    state: directory

