- name: Install Nginx
  yum:
   name: nginx
   state: latest

- name: Start Nginx Service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Copy AzureDevops Reop File
  copy:
    src: azurecli.repo
    dest: /etc/yum.repos.d

- name: Install Azure CLI
  yum:
    name: [ "azure-cli", "libicu" ]
    state: latest

- name: Install Azure Devops Extensions
  shell: az extension add --name azure-devops


