- name: Install Nginx
  yum:
    name: nginx
    state: latest

- name: Start Nginx Service
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Download RPM
  shell: rpm --import https://packages.microsoft.com/keys/microsoft.asc

- name: Copy Azure DevOps Repo File
  copy:
    src: azure-cli.repo
    dest: /etc/yum.repos.d

- name: Install Azure CLI
  yum:
    name: [ "azure-cli", "libicu" ]
    state: latest

- name: Download Azure Extentions
  shell: az extension add --name azure-devops



