- name: Copy Azure DevOps Repo File
  copy:
    src: azure-cli.repo
    dest: /etc/yum.repos.d

- name: Install Azure CLI
  yum:
    name: [ "azure-cli", "libicu" ]
    state: latest

- name: Download Azure Extentions
  shell: az extension add --name azure-devops

- name: Azure Login
  shell: echo {{PAT}} | az devops login --organization https://dev.azure.com/shehan567/